// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: metadata.sql

package db

import (
	"context"
)

const createMetaData = `-- name: CreateMetaData :exec
INSERT INTO metadata (
  "user_id", "org", data_type, data_value
) VALUES (
  $1, $2, $3, $4
)
`

type CreateMetaDataParams struct {
	UserID    int64  `json:"user_id"`
	Org       int64  `json:"org"`
	DataType  string `json:"data_type"`
	DataValue []byte `json:"data_value"`
}

// CreateMetaData
//
//	INSERT INTO metadata (
//	  "user_id", "org", data_type, data_value
//	) VALUES (
//	  $1, $2, $3, $4
//	)
func (q *Queries) CreateMetaData(ctx context.Context, arg CreateMetaDataParams) error {
	_, err := q.db.Exec(ctx, createMetaData,
		arg.UserID,
		arg.Org,
		arg.DataType,
		arg.DataValue,
	)
	return err
}
