// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID            int64              `json:"id"`
	Uuid          string             `json:"uuid"`
	CommitID      int64              `json:"commit_id"`
	AlertConfigID int64              `json:"alert_config_id"`
	FilePath      string             `json:"file_path"`
	OrgID         int64              `json:"org_id"`
	Status        string             `json:"status"`
	Source        string             `json:"source"`
	FileName      string             `json:"file_name"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type AlertConfig struct {
	ID        int64              `json:"id"`
	Uuid      string             `json:"uuid"`
	Type      string             `json:"type"`
	Matcher   string             `json:"matcher"`
	Severity  string             `json:"severity"`
	AlertType string             `json:"alert_type"`
	Org       int64              `json:"org"`
	Regex     pgtype.Text        `json:"regex"`
	Desc      pgtype.Text        `json:"desc"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CommitWebhook struct {
	ID              int64              `json:"id"`
	CommitID        string             `json:"commit_id"`
	Uuid            string             `json:"uuid"`
	RepoID          int64              `json:"repo_id"`
	Org             int64              `json:"org"`
	AuthorName      string             `json:"author_name"`
	AuthorEmail     string             `json:"author_email"`
	ScannedByCli    pgtype.Bool        `json:"scanned_by_cli"`
	ScannedByRunner pgtype.Bool        `json:"scanned_by_runner"`
	Provider        string             `json:"provider"`
	CommitTime      pgtype.Timestamptz `json:"commit_time"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type CommitsCli struct {
	ID          int64              `json:"id"`
	CommitID    string             `json:"commit_id"`
	Uuid        string             `json:"uuid"`
	Org         int64              `json:"org"`
	UserID      int64              `json:"user_id"`
	Repo        pgtype.Int8        `json:"repo"`
	Author      pgtype.Text        `json:"author"`
	UserRepoUrl string             `json:"user_repo_url"`
	Source      string             `json:"source"`
	Sessionid   string             `json:"sessionid"`
	CommitTime  pgtype.Timestamptz `json:"commit_time"`
	PushTime    pgtype.Timestamptz `json:"push_time"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type GitProvider struct {
	ID        int64              `json:"id"`
	Uuid      string             `json:"uuid"`
	OrgName   string             `json:"org_name"`
	OrgID     int64              `json:"org_id"`
	Type      string             `json:"type"`
	VcsOrgID  int64              `json:"vcs_org_id"`
	InstallID int64              `json:"install_id"`
	Token     pgtype.Text        `json:"token"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Metadata struct {
	ID        int64              `json:"id"`
	Uuid      string             `json:"uuid"`
	DataType  string             `json:"data_type"`
	Org       int64              `json:"org"`
	DataValue []byte             `json:"data_value"`
	UserID    int64              `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Organisation struct {
	ID          int64              `json:"id"`
	Uuid        string             `json:"uuid"`
	Name        string             `json:"name"`
	OrgUnit     pgtype.Int8        `json:"org_unit"`
	Provider    string             `json:"provider"`
	Creds       []byte             `json:"creds"`
	Tier        pgtype.Text        `json:"tier"`
	Domain      pgtype.Text        `json:"domain"`
	GithubOrgID pgtype.Int8        `json:"github_org_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Repo struct {
	ID        int64              `json:"id"`
	Uuid      string             `json:"uuid"`
	Name      string             `json:"name"`
	Repourl   string             `json:"repourl"`
	Provider  string             `json:"provider"`
	Org       int64              `json:"org"`
	VcsRepoID int64              `json:"vcs_repo_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID             int64              `json:"id"`
	Uuid           string             `json:"uuid"`
	Email          string             `json:"email"`
	HashPassword   string             `json:"hash_password"`
	Provider       string             `json:"provider"`
	Org            int64              `json:"org"`
	Role           pgtype.Text        `json:"role"`
	GithubUserID   pgtype.Int8        `json:"github_user_id"`
	GithubUserName pgtype.Text        `json:"github_user_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
