CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE "organisations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL DEFAULT (uuid_generate_v4()),
  "name" varchar(255) NOT NULL,
  "org_unit" bigint,
  "provider" varchar(50) NOT NULL,
  "creds" jsonb,
  "tier" varchar(50),
  "domain" varchar(255),
  "github_org_id" bigint,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "commit_webhooks" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "commit_id" varchar NOT NULL UNIQUE,
  "uuid" uuid UNIQUE NOT NULL DEFAULT (uuid_generate_v4()),
  "repo_id" bigint NOT NULL,
  "org" bigint NOT NULL,
  "author_name" varchar(255) NOT NULL,
  "author_email" varchar(320) NOT NULL,
  "scanned_by_cli" bool,
  "scanned_by_runner" bool,
  "provider" varchar(50) NOT NULL,
  "commit_time" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

-- CREATE TABLE "orgunits" (
--   "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   "uuid" uuid UNIQUE NOT NULL DEFAULT (uuid_generate_v4()),
--   "name" varchar(255) NOT NULL,
--   "created_at" timestamptz NOT NULL DEFAULT (now()),
--   "updated_ai" timestamptz NOT NULL DEFAULT (now())
-- );

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL DEFAULT (uuid_generate_v4()),
  "email" varchar(320) UNIQUE NOT NULL,
  "hash_password" varchar(255) NOT NULL,
  "provider" varchar(255) NOT NULL,
  "org" bigint NOT NULL,
  "role" varchar(50) DEFAULT 'user',
  "github_user_id" bigint,
  "github_user_name" varchar(255),
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "repos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL DEFAULT (uuid_generate_v4()),
  "name" varchar(255) NOT NULL,
  "repourl" varchar NOT NULL,
  "provider" varchar(50) NOT NULL,
  "org" bigint NOT NULL,
  "vcs_repo_id" bigint NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "commits_cli" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "commit_id" varchar(40) NOT NULL UNIQUE,
  "uuid" uuid UNIQUE NOT NULL DEFAULT (uuid_generate_v4()),
  "org" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "repo" bigint,
  "author" varchar(255),
  "user_repo_url" varchar NOT NULL,
  "source" varchar(100) NOT NULL,
  "sessionid" varchar(255) NOT NULL,
  "commit_time" timestamptz NOT NULL,
  "push_time" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "alerts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL DEFAULT (uuid_generate_v4()),
  "commit_id" bigint NOT NULL,
  "alert_config_id" bigint NOT NULL,
  "file_path" varchar NOT NULL,
  "org_id" bigint NOT NULL,
  "status" varchar NOT NULL,
  "source" varchar NOT NULL,
  "file_name" varchar NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "alert_config" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL DEFAULT (uuid_generate_v4()),
  "type" varchar NOT NULL,
  "matcher" varchar NOT NULL,
  "severity" varchar NOT NULL,
  "alert_type" varchar NOT NULL,
  "org" bigint NOT NULL,
  "regex" varchar,
  "desc" varchar,
  "is_active" bool,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "git_provider" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL DEFAULT (uuid_generate_v4()),
  "org_name" varchar NOT NULL,
  "org_id" bigint NOT NULL,
  "type" varchar NOT NULL,
  "vcs_org_id" bigint NOT NULL,
  "install_id" bigint NOT NULL,
  "token" varchar,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "metadata" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL DEFAULT (uuid_generate_v4()),
  "data_type" varchar(100) NOT NULL,
  "org" bigint NOT NULL,
  "data_value" jsonb,
  "user_id" bigint NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

ALTER TABLE "commit_webhooks" ADD FOREIGN KEY ("repo_id") REFERENCES "repos" ("id");

ALTER TABLE "commit_webhooks" ADD FOREIGN KEY ("org") REFERENCES "organisations" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("org") REFERENCES "organisations" ("id");

ALTER TABLE "repos" ADD FOREIGN KEY ("org") REFERENCES "organisations" ("id");

ALTER TABLE "commits_cli" ADD FOREIGN KEY ("org") REFERENCES "organisations" ("id");

ALTER TABLE "commits_cli" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "commits_cli" ADD FOREIGN KEY ("repo") REFERENCES "repos" ("id");

ALTER TABLE "alerts" ADD FOREIGN KEY ("commit_id") REFERENCES "commits_cli" ("id");

ALTER TABLE "alerts" ADD FOREIGN KEY ("alert_config_id") REFERENCES "alert_config" ("id");

ALTER TABLE "alert_config" ADD FOREIGN KEY ("org") REFERENCES "organisations" ("id");

ALTER TABLE "git_provider" ADD FOREIGN KEY ("org_id") REFERENCES "organisations" ("id");

ALTER TABLE "metadata" ADD FOREIGN KEY ("org") REFERENCES "organisations" ("id");

ALTER TABLE "metadata" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
